/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_winMain (void)
{
  GtkWidget *winMain;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *menuConnect;
  GtkWidget *image27;
  GtkWidget *menuDisconnect;
  GtkWidget *image28;
  GtkWidget *separatormenuitem1;
  GtkWidget *menuQuit;
  GtkWidget *image29;
  GtkWidget *menuSettings;
  GtkWidget *menuSettings_menu;
  GtkWidget *chkAcc;
  GtkWidget *chkIR;
  GtkWidget *chkExt;
  GtkWidget *menuControls;
  GtkWidget *menuControls_menu;
  GtkWidget *chkLED1;
  GtkWidget *chkLED2;
  GtkWidget *chkLED3;
  GtkWidget *chkLED4;
  GtkWidget *separator1;
  GtkWidget *chkRumble;
  GtkWidget *menuView;
  GtkWidget *menuView_menu;
  GtkWidget *menuRW;
  GtkWidget *menuHelp;
  GtkWidget *menuHelp_menu;
  GtkWidget *menuAbout;
  GtkWidget *hbox1;
  GtkWidget *frame1;
  GtkWidget *alignment1;
  GtkWidget *table1;
  GtkWidget *alignment3;
  GtkWidget *evUp;
  GtkWidget *lblUp;
  GtkWidget *alignment4;
  GtkWidget *evLeft;
  GtkWidget *lblLeft;
  GtkWidget *alignment5;
  GtkWidget *evRight;
  GtkWidget *lblRight;
  GtkWidget *alignment6;
  GtkWidget *evDown;
  GtkWidget *lblDown;
  GtkWidget *alignment7;
  GtkWidget *evA;
  GtkWidget *lblA;
  GtkWidget *alignment9;
  GtkWidget *evB;
  GtkWidget *lblB;
  GtkWidget *alignment10;
  GtkWidget *evMinus;
  GtkWidget *lblMinus;
  GtkWidget *alignment11;
  GtkWidget *evHome;
  GtkWidget *lblHome;
  GtkWidget *alignment12;
  GtkWidget *evPlus;
  GtkWidget *lblPlus;
  GtkWidget *alignment13;
  GtkWidget *ev1;
  GtkWidget *lbl1;
  GtkWidget *alignment14;
  GtkWidget *ev2;
  GtkWidget *lbl2;
  GtkWidget *label1;
  GtkWidget *frame2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *table4;
  GtkWidget *progAccX;
  GtkWidget *progAccY;
  GtkWidget *progAccZ;
  GtkWidget *lblAccX;
  GtkWidget *lblAccXVal;
  GtkWidget *lblAccY;
  GtkWidget *lblAccYVal;
  GtkWidget *lblAccZ;
  GtkWidget *lblAccZVal;
  GtkWidget *lblPitch;
  GtkWidget *lblPitchVal;
  GtkWidget *lblRoll;
  GtkWidget *lblRollVal;
  GtkWidget *lblAcc;
  GtkWidget *lblAccVal;
  GtkWidget *btnBeep;
  GtkWidget *frame3;
  GtkWidget *drawIR;
  GtkWidget *lblIR;
  GtkWidget *label2;
  GtkWidget *hbox10;
  GtkWidget *frame4;
  GtkWidget *alignment28;
  GtkWidget *hbox12;
  GtkWidget *vbox4;
  GtkWidget *drawNCStick;
  GtkWidget *hbox13;
  GtkWidget *evNCC;
  GtkWidget *lblNCC;
  GtkWidget *evNCZ;
  GtkWidget *lblNCZ;
  GtkWidget *table8;
  GtkWidget *lblNCAccX;
  GtkWidget *lblNCAccY;
  GtkWidget *lblNCAccZ;
  GtkWidget *lblNCAcc;
  GtkWidget *lblNCRoll;
  GtkWidget *lblNCPitch;
  GtkWidget *lblNCAccXVal;
  GtkWidget *lblNCAccYVal;
  GtkWidget *lblNCAccZVal;
  GtkWidget *lblNCAccVal;
  GtkWidget *lblNCRollVal;
  GtkWidget *lblNCPitchVal;
  GtkWidget *progNCAccX;
  GtkWidget *progNCAccZ;
  GtkWidget *progNCAccY;
  GtkWidget *lblNC;
  GtkWidget *frame5;
  GtkWidget *alignment29;
  GtkWidget *vbox5;
  GtkWidget *table9;
  GtkWidget *alignment15;
  GtkWidget *evCCLeft;
  GtkWidget *lblCCLeft;
  GtkWidget *alignment16;
  GtkWidget *evCCUp;
  GtkWidget *lblCCUp;
  GtkWidget *alignment17;
  GtkWidget *evCCDown;
  GtkWidget *lblCCDown;
  GtkWidget *alignment18;
  GtkWidget *evCCRight;
  GtkWidget *lblCCRight;
  GtkWidget *alignment19;
  GtkWidget *evCCMinus;
  GtkWidget *lblCCMinus;
  GtkWidget *alignment20;
  GtkWidget *evCCHome;
  GtkWidget *lblCCHome;
  GtkWidget *alignment21;
  GtkWidget *evCCPlus;
  GtkWidget *lblCCPlus;
  GtkWidget *alignment22;
  GtkWidget *evCCZL;
  GtkWidget *lblCCZL;
  GtkWidget *alignment23;
  GtkWidget *evCCZR;
  GtkWidget *lblCCZR;
  GtkWidget *alignment24;
  GtkWidget *evCCX;
  GtkWidget *lblCCX;
  GtkWidget *alignment25;
  GtkWidget *evCCY;
  GtkWidget *lblCCY;
  GtkWidget *alignment26;
  GtkWidget *evCCB;
  GtkWidget *lblCCB;
  GtkWidget *alignment27;
  GtkWidget *evCCA;
  GtkWidget *lblCCA;
  GtkWidget *hbox15;
  GtkWidget *drawCCLStick;
  GtkWidget *drawCCRStick;
  GtkWidget *table10;
  GtkWidget *lblCCLVal;
  GtkWidget *lblCCRVal;
  GtkWidget *progCCL;
  GtkWidget *progCCR;
  GtkWidget *evCCR;
  GtkWidget *lblCCR;
  GtkWidget *evCCL;
  GtkWidget *lblCCL;
  GtkWidget *lblClassic;
  GtkWidget *hbox11;
  GtkWidget *statConnection;
  GtkWidget *statBattery;
  GtkWidget *statExtension;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  winMain = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (winMain, "winMain");
  gtk_window_set_title (GTK_WINDOW (winMain), "wmgui");

  vbox1 = gtk_vbox_new (FALSE, 3);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (winMain), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar1, "menubar1");
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic ("_File");
  gtk_widget_set_name (menuitem1, "menuitem1");
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_widget_set_name (menuitem1_menu, "menuitem1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  menuConnect = gtk_image_menu_item_new_with_mnemonic ("_Connect");
  gtk_widget_set_name (menuConnect, "menuConnect");
  gtk_widget_show (menuConnect);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), menuConnect);
  gtk_widget_add_accelerator (menuConnect, "activate", accel_group,
                              GDK_C, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image27 = gtk_image_new_from_stock ("gtk-connect", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image27, "image27");
  gtk_widget_show (image27);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (menuConnect), image27);

  menuDisconnect = gtk_image_menu_item_new_with_mnemonic ("_Disconnect");
  gtk_widget_set_name (menuDisconnect, "menuDisconnect");
  gtk_widget_show (menuDisconnect);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), menuDisconnect);
  gtk_widget_add_accelerator (menuDisconnect, "activate", accel_group,
                              GDK_D, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image28 = gtk_image_new_from_stock ("gtk-disconnect", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image28, "image28");
  gtk_widget_show (image28);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (menuDisconnect), image28);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_set_name (separatormenuitem1, "separatormenuitem1");
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  menuQuit = gtk_image_menu_item_new_with_mnemonic ("_Quit");
  gtk_widget_set_name (menuQuit, "menuQuit");
  gtk_widget_show (menuQuit);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), menuQuit);
  gtk_widget_add_accelerator (menuQuit, "activate", accel_group,
                              GDK_Q, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image29 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image29, "image29");
  gtk_widget_show (image29);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (menuQuit), image29);

  menuSettings = gtk_menu_item_new_with_mnemonic ("_Settings");
  gtk_widget_set_name (menuSettings, "menuSettings");
  gtk_widget_show (menuSettings);
  gtk_container_add (GTK_CONTAINER (menubar1), menuSettings);

  menuSettings_menu = gtk_menu_new ();
  gtk_widget_set_name (menuSettings_menu, "menuSettings_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuSettings), menuSettings_menu);

  chkAcc = gtk_check_menu_item_new_with_mnemonic ("_Acc Data");
  gtk_widget_set_name (chkAcc, "chkAcc");
  gtk_widget_show (chkAcc);
  gtk_container_add (GTK_CONTAINER (menuSettings_menu), chkAcc);
  gtk_widget_add_accelerator (chkAcc, "activate", accel_group,
                              GDK_A, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  chkIR = gtk_check_menu_item_new_with_mnemonic ("_IR Data");
  gtk_widget_set_name (chkIR, "chkIR");
  gtk_widget_show (chkIR);
  gtk_container_add (GTK_CONTAINER (menuSettings_menu), chkIR);
  gtk_widget_add_accelerator (chkIR, "activate", accel_group,
                              GDK_I, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  chkExt = gtk_check_menu_item_new_with_mnemonic ("_Extension Data");
  gtk_widget_set_name (chkExt, "chkExt");
  gtk_widget_show (chkExt);
  gtk_container_add (GTK_CONTAINER (menuSettings_menu), chkExt);
  gtk_widget_add_accelerator (chkExt, "activate", accel_group,
                              GDK_E, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  menuControls = gtk_menu_item_new_with_mnemonic ("_Controls");
  gtk_widget_set_name (menuControls, "menuControls");
  gtk_widget_show (menuControls);
  gtk_container_add (GTK_CONTAINER (menubar1), menuControls);

  menuControls_menu = gtk_menu_new ();
  gtk_widget_set_name (menuControls_menu, "menuControls_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuControls), menuControls_menu);

  chkLED1 = gtk_check_menu_item_new_with_mnemonic ("LED _1");
  gtk_widget_set_name (chkLED1, "chkLED1");
  gtk_widget_show (chkLED1);
  gtk_container_add (GTK_CONTAINER (menuControls_menu), chkLED1);
  gtk_widget_add_accelerator (chkLED1, "activate", accel_group,
                              GDK_1, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  chkLED2 = gtk_check_menu_item_new_with_mnemonic ("LED _2");
  gtk_widget_set_name (chkLED2, "chkLED2");
  gtk_widget_show (chkLED2);
  gtk_container_add (GTK_CONTAINER (menuControls_menu), chkLED2);
  gtk_widget_add_accelerator (chkLED2, "activate", accel_group,
                              GDK_2, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  chkLED3 = gtk_check_menu_item_new_with_mnemonic ("LED _3");
  gtk_widget_set_name (chkLED3, "chkLED3");
  gtk_widget_show (chkLED3);
  gtk_container_add (GTK_CONTAINER (menuControls_menu), chkLED3);
  gtk_widget_add_accelerator (chkLED3, "activate", accel_group,
                              GDK_3, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  chkLED4 = gtk_check_menu_item_new_with_mnemonic ("LED _4");
  gtk_widget_set_name (chkLED4, "chkLED4");
  gtk_widget_show (chkLED4);
  gtk_container_add (GTK_CONTAINER (menuControls_menu), chkLED4);
  gtk_widget_add_accelerator (chkLED4, "activate", accel_group,
                              GDK_4, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  separator1 = gtk_separator_menu_item_new ();
  gtk_widget_set_name (separator1, "separator1");
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (menuControls_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  chkRumble = gtk_check_menu_item_new_with_mnemonic ("_Rumble");
  gtk_widget_set_name (chkRumble, "chkRumble");
  gtk_widget_show (chkRumble);
  gtk_container_add (GTK_CONTAINER (menuControls_menu), chkRumble);
  gtk_widget_add_accelerator (chkRumble, "activate", accel_group,
                              GDK_R, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  menuView = gtk_menu_item_new_with_mnemonic ("_View");
  gtk_widget_set_name (menuView, "menuView");
  gtk_widget_show (menuView);
  gtk_container_add (GTK_CONTAINER (menubar1), menuView);

  menuView_menu = gtk_menu_new ();
  gtk_widget_set_name (menuView_menu, "menuView_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuView), menuView_menu);

  menuRW = gtk_menu_item_new_with_mnemonic ("_Memory Read/Write");
  gtk_widget_set_name (menuRW, "menuRW");
  gtk_widget_show (menuRW);
  gtk_container_add (GTK_CONTAINER (menuView_menu), menuRW);
  gtk_widget_add_accelerator (menuRW, "activate", accel_group,
                              GDK_M, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  menuHelp = gtk_menu_item_new_with_mnemonic ("_Help");
  gtk_widget_set_name (menuHelp, "menuHelp");
  gtk_widget_show (menuHelp);
  gtk_container_add (GTK_CONTAINER (menubar1), menuHelp);

  menuHelp_menu = gtk_menu_new ();
  gtk_widget_set_name (menuHelp_menu, "menuHelp_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuHelp), menuHelp_menu);

  menuAbout = gtk_menu_item_new_with_mnemonic ("_About");
  gtk_widget_set_name (menuAbout, "menuAbout");
  gtk_widget_show (menuAbout);
  gtk_container_add (GTK_CONTAINER (menuHelp_menu), menuAbout);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame1, "frame1");
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (hbox1), frame1, TRUE, TRUE, 3);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment1, "alignment1");
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (frame1), alignment1);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 0, 0, 12, 0);

  table1 = gtk_table_new (6, 3, TRUE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (alignment1), table1);

  alignment3 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment3, "alignment3");
  gtk_widget_show (alignment3);
  gtk_table_attach (GTK_TABLE (table1), alignment3, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  evUp = gtk_event_box_new ();
  gtk_widget_set_name (evUp, "evUp");
  gtk_widget_show (evUp);
  gtk_container_add (GTK_CONTAINER (alignment3), evUp);

  lblUp = gtk_label_new ("Up");
  gtk_widget_set_name (lblUp, "lblUp");
  gtk_widget_show (lblUp);
  gtk_container_add (GTK_CONTAINER (evUp), lblUp);

  alignment4 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment4, "alignment4");
  gtk_widget_show (alignment4);
  gtk_table_attach (GTK_TABLE (table1), alignment4, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  evLeft = gtk_event_box_new ();
  gtk_widget_set_name (evLeft, "evLeft");
  gtk_widget_show (evLeft);
  gtk_container_add (GTK_CONTAINER (alignment4), evLeft);

  lblLeft = gtk_label_new ("Left");
  gtk_widget_set_name (lblLeft, "lblLeft");
  gtk_widget_show (lblLeft);
  gtk_container_add (GTK_CONTAINER (evLeft), lblLeft);

  alignment5 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment5, "alignment5");
  gtk_widget_show (alignment5);
  gtk_table_attach (GTK_TABLE (table1), alignment5, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  evRight = gtk_event_box_new ();
  gtk_widget_set_name (evRight, "evRight");
  gtk_widget_show (evRight);
  gtk_container_add (GTK_CONTAINER (alignment5), evRight);

  lblRight = gtk_label_new ("Right");
  gtk_widget_set_name (lblRight, "lblRight");
  gtk_widget_show (lblRight);
  gtk_container_add (GTK_CONTAINER (evRight), lblRight);

  alignment6 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment6, "alignment6");
  gtk_widget_show (alignment6);
  gtk_table_attach (GTK_TABLE (table1), alignment6, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  evDown = gtk_event_box_new ();
  gtk_widget_set_name (evDown, "evDown");
  gtk_widget_show (evDown);
  gtk_container_add (GTK_CONTAINER (alignment6), evDown);

  lblDown = gtk_label_new ("Down");
  gtk_widget_set_name (lblDown, "lblDown");
  gtk_widget_show (lblDown);
  gtk_container_add (GTK_CONTAINER (evDown), lblDown);

  alignment7 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment7, "alignment7");
  gtk_widget_show (alignment7);
  gtk_table_attach (GTK_TABLE (table1), alignment7, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  evA = gtk_event_box_new ();
  gtk_widget_set_name (evA, "evA");
  gtk_widget_show (evA);
  gtk_container_add (GTK_CONTAINER (alignment7), evA);

  lblA = gtk_label_new ("A");
  gtk_widget_set_name (lblA, "lblA");
  gtk_widget_show (lblA);
  gtk_container_add (GTK_CONTAINER (evA), lblA);

  alignment9 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment9, "alignment9");
  gtk_widget_show (alignment9);
  gtk_table_attach (GTK_TABLE (table1), alignment9, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  evB = gtk_event_box_new ();
  gtk_widget_set_name (evB, "evB");
  gtk_widget_show (evB);
  gtk_container_add (GTK_CONTAINER (alignment9), evB);

  lblB = gtk_label_new ("B");
  gtk_widget_set_name (lblB, "lblB");
  gtk_widget_show (lblB);
  gtk_container_add (GTK_CONTAINER (evB), lblB);

  alignment10 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment10, "alignment10");
  gtk_widget_show (alignment10);
  gtk_table_attach (GTK_TABLE (table1), alignment10, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  evMinus = gtk_event_box_new ();
  gtk_widget_set_name (evMinus, "evMinus");
  gtk_widget_show (evMinus);
  gtk_container_add (GTK_CONTAINER (alignment10), evMinus);

  lblMinus = gtk_label_new ("-");
  gtk_widget_set_name (lblMinus, "lblMinus");
  gtk_widget_show (lblMinus);
  gtk_container_add (GTK_CONTAINER (evMinus), lblMinus);

  alignment11 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment11, "alignment11");
  gtk_widget_show (alignment11);
  gtk_table_attach (GTK_TABLE (table1), alignment11, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  evHome = gtk_event_box_new ();
  gtk_widget_set_name (evHome, "evHome");
  gtk_widget_show (evHome);
  gtk_container_add (GTK_CONTAINER (alignment11), evHome);

  lblHome = gtk_label_new ("Home");
  gtk_widget_set_name (lblHome, "lblHome");
  gtk_widget_show (lblHome);
  gtk_container_add (GTK_CONTAINER (evHome), lblHome);

  alignment12 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment12, "alignment12");
  gtk_widget_show (alignment12);
  gtk_table_attach (GTK_TABLE (table1), alignment12, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  evPlus = gtk_event_box_new ();
  gtk_widget_set_name (evPlus, "evPlus");
  gtk_widget_show (evPlus);
  gtk_container_add (GTK_CONTAINER (alignment12), evPlus);

  lblPlus = gtk_label_new ("+");
  gtk_widget_set_name (lblPlus, "lblPlus");
  gtk_widget_show (lblPlus);
  gtk_container_add (GTK_CONTAINER (evPlus), lblPlus);

  alignment13 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment13, "alignment13");
  gtk_widget_show (alignment13);
  gtk_table_attach (GTK_TABLE (table1), alignment13, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  ev1 = gtk_event_box_new ();
  gtk_widget_set_name (ev1, "ev1");
  gtk_widget_show (ev1);
  gtk_container_add (GTK_CONTAINER (alignment13), ev1);

  lbl1 = gtk_label_new ("1");
  gtk_widget_set_name (lbl1, "lbl1");
  gtk_widget_show (lbl1);
  gtk_container_add (GTK_CONTAINER (ev1), lbl1);

  alignment14 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment14, "alignment14");
  gtk_widget_show (alignment14);
  gtk_table_attach (GTK_TABLE (table1), alignment14, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  ev2 = gtk_event_box_new ();
  gtk_widget_set_name (ev2, "ev2");
  gtk_widget_show (ev2);
  gtk_container_add (GTK_CONTAINER (alignment14), ev2);

  lbl2 = gtk_label_new ("2");
  gtk_widget_set_name (lbl2, "lbl2");
  gtk_widget_show (lbl2);
  gtk_container_add (GTK_CONTAINER (ev2), lbl2);

  label1 = gtk_label_new ("<b>Buttons</b>");
  gtk_widget_set_name (label1, "label1");
  gtk_widget_show (label1);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label1);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame2, "frame2");
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (hbox1), frame2, TRUE, TRUE, 3);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment2, "alignment2");
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (frame2), alignment2);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 0, 0, 12, 0);

  hbox2 = gtk_hbox_new (TRUE, 6);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  table4 = gtk_table_new (6, 3, FALSE);
  gtk_widget_set_name (table4, "table4");
  gtk_widget_show (table4);
  gtk_box_pack_start (GTK_BOX (hbox2), table4, TRUE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table4), 3);

  progAccX = gtk_progress_bar_new ();
  gtk_widget_set_name (progAccX, "progAccX");
  gtk_widget_show (progAccX);
  gtk_table_attach (GTK_TABLE (table4), progAccX, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (progAccX, FALSE);

  progAccY = gtk_progress_bar_new ();
  gtk_widget_set_name (progAccY, "progAccY");
  gtk_widget_show (progAccY);
  gtk_table_attach (GTK_TABLE (table4), progAccY, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (progAccY, FALSE);

  progAccZ = gtk_progress_bar_new ();
  gtk_widget_set_name (progAccZ, "progAccZ");
  gtk_widget_show (progAccZ);
  gtk_table_attach (GTK_TABLE (table4), progAccZ, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (progAccZ, FALSE);

  lblAccX = gtk_label_new ("X:");
  gtk_widget_set_name (lblAccX, "lblAccX");
  gtk_widget_show (lblAccX);
  gtk_table_attach (GTK_TABLE (table4), lblAccX, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (lblAccX, FALSE);
  gtk_label_set_justify (GTK_LABEL (lblAccX), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (lblAccX), 0, 0.5);

  lblAccXVal = gtk_label_new ("0");
  gtk_widget_set_name (lblAccXVal, "lblAccXVal");
  gtk_widget_show (lblAccXVal);
  gtk_table_attach (GTK_TABLE (table4), lblAccXVal, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lblAccXVal, 35, -1);
  gtk_widget_set_sensitive (lblAccXVal, FALSE);
  gtk_misc_set_alignment (GTK_MISC (lblAccXVal), 0, 0.5);

  lblAccY = gtk_label_new ("Y:");
  gtk_widget_set_name (lblAccY, "lblAccY");
  gtk_widget_show (lblAccY);
  gtk_table_attach (GTK_TABLE (table4), lblAccY, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (lblAccY, FALSE);
  gtk_label_set_justify (GTK_LABEL (lblAccY), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (lblAccY), 0, 0.5);

  lblAccYVal = gtk_label_new ("0");
  gtk_widget_set_name (lblAccYVal, "lblAccYVal");
  gtk_widget_show (lblAccYVal);
  gtk_table_attach (GTK_TABLE (table4), lblAccYVal, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lblAccYVal, 35, -1);
  gtk_widget_set_sensitive (lblAccYVal, FALSE);
  gtk_misc_set_alignment (GTK_MISC (lblAccYVal), 0, 0.5);

  lblAccZ = gtk_label_new ("Z:");
  gtk_widget_set_name (lblAccZ, "lblAccZ");
  gtk_widget_show (lblAccZ);
  gtk_table_attach (GTK_TABLE (table4), lblAccZ, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (lblAccZ, FALSE);
  gtk_label_set_justify (GTK_LABEL (lblAccZ), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (lblAccZ), 0, 0.5);

  lblAccZVal = gtk_label_new ("0");
  gtk_widget_set_name (lblAccZVal, "lblAccZVal");
  gtk_widget_show (lblAccZVal);
  gtk_table_attach (GTK_TABLE (table4), lblAccZVal, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lblAccZVal, 35, -1);
  gtk_widget_set_sensitive (lblAccZVal, FALSE);
  gtk_misc_set_alignment (GTK_MISC (lblAccZVal), 0, 0.5);

  lblPitch = gtk_label_new ("Pitch:");
  gtk_widget_set_name (lblPitch, "lblPitch");
  gtk_widget_show (lblPitch);
  gtk_table_attach (GTK_TABLE (table4), lblPitch, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (lblPitch, FALSE);
  gtk_label_set_justify (GTK_LABEL (lblPitch), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (lblPitch), 0, 0.5);

  lblPitchVal = gtk_label_new ("0");
  gtk_widget_set_name (lblPitchVal, "lblPitchVal");
  gtk_widget_show (lblPitchVal);
  gtk_table_attach (GTK_TABLE (table4), lblPitchVal, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lblPitchVal, 35, -1);
  gtk_widget_set_sensitive (lblPitchVal, FALSE);
  gtk_misc_set_alignment (GTK_MISC (lblPitchVal), 0, 0.5);

  lblRoll = gtk_label_new ("Roll:");
  gtk_widget_set_name (lblRoll, "lblRoll");
  gtk_widget_show (lblRoll);
  gtk_table_attach (GTK_TABLE (table4), lblRoll, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (lblRoll, FALSE);
  gtk_label_set_justify (GTK_LABEL (lblRoll), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (lblRoll), 0, 0.5);

  lblRollVal = gtk_label_new ("0");
  gtk_widget_set_name (lblRollVal, "lblRollVal");
  gtk_widget_show (lblRollVal);
  gtk_table_attach (GTK_TABLE (table4), lblRollVal, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lblRollVal, 35, -1);
  gtk_widget_set_sensitive (lblRollVal, FALSE);
  gtk_misc_set_alignment (GTK_MISC (lblRollVal), 0, 0.5);

  lblAcc = gtk_label_new ("Acc:");
  gtk_widget_set_name (lblAcc, "lblAcc");
  gtk_widget_show (lblAcc);
  gtk_table_attach (GTK_TABLE (table4), lblAcc, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (lblAcc, FALSE);
  gtk_misc_set_alignment (GTK_MISC (lblAcc), 0, 0.5);

  lblAccVal = gtk_label_new ("0");
  gtk_widget_set_name (lblAccVal, "lblAccVal");
  gtk_widget_show (lblAccVal);
  gtk_table_attach (GTK_TABLE (table4), lblAccVal, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lblAccVal, 35, -1);
  gtk_widget_set_sensitive (lblAccVal, FALSE);
  gtk_misc_set_alignment (GTK_MISC (lblAccVal), 0, 0.5);

  btnBeep = gtk_button_new_with_mnemonic ("Beep");
  gtk_widget_set_name (btnBeep, "btnBeep");
  gtk_table_attach (GTK_TABLE (table4), btnBeep, 2, 3, 4, 5,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame3, "frame3");
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (hbox2), frame3, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame3), 4);
  gtk_frame_set_shadow_type (GTK_FRAME (frame3), GTK_SHADOW_IN);

  drawIR = gtk_drawing_area_new ();
  gtk_widget_set_name (drawIR, "drawIR");
  gtk_widget_show (drawIR);
  gtk_container_add (GTK_CONTAINER (frame3), drawIR);

  lblIR = gtk_label_new ("IR");
  gtk_widget_set_name (lblIR, "lblIR");
  gtk_widget_show (lblIR);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), lblIR);
  gtk_widget_set_sensitive (lblIR, FALSE);
  gtk_label_set_use_markup (GTK_LABEL (lblIR), TRUE);

  label2 = gtk_label_new ("<b>Motion Sensors</b>");
  gtk_widget_set_name (label2, "label2");
  gtk_widget_show (label2);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label2);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox10, "hbox10");
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox10, FALSE, FALSE, 0);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame4, "frame4");
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (hbox10), frame4, TRUE, TRUE, 3);

  alignment28 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment28, "alignment28");
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (frame4), alignment28);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment28), 0, 0, 12, 0);

  hbox12 = gtk_hbox_new (FALSE, 4);
  gtk_widget_set_name (hbox12, "hbox12");
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox12);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox4, "vbox4");
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox12), vbox4, TRUE, TRUE, 0);

  drawNCStick = gtk_drawing_area_new ();
  gtk_widget_set_name (drawNCStick, "drawNCStick");
  gtk_widget_show (drawNCStick);
  gtk_box_pack_start (GTK_BOX (vbox4), drawNCStick, TRUE, FALSE, 0);
  gtk_widget_set_size_request (drawNCStick, 50, 50);

  hbox13 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox13, "hbox13");
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox13, TRUE, FALSE, 0);

  evNCC = gtk_event_box_new ();
  gtk_widget_set_name (evNCC, "evNCC");
  gtk_widget_show (evNCC);
  gtk_box_pack_start (GTK_BOX (hbox13), evNCC, TRUE, TRUE, 0);

  lblNCC = gtk_label_new ("C");
  gtk_widget_set_name (lblNCC, "lblNCC");
  gtk_widget_show (lblNCC);
  gtk_container_add (GTK_CONTAINER (evNCC), lblNCC);

  evNCZ = gtk_event_box_new ();
  gtk_widget_set_name (evNCZ, "evNCZ");
  gtk_widget_show (evNCZ);
  gtk_box_pack_start (GTK_BOX (hbox13), evNCZ, TRUE, TRUE, 0);

  lblNCZ = gtk_label_new ("Z");
  gtk_widget_set_name (lblNCZ, "lblNCZ");
  gtk_widget_show (lblNCZ);
  gtk_container_add (GTK_CONTAINER (evNCZ), lblNCZ);

  table8 = gtk_table_new (6, 3, FALSE);
  gtk_widget_set_name (table8, "table8");
  gtk_widget_show (table8);
  gtk_box_pack_start (GTK_BOX (hbox12), table8, FALSE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table8), 3);

  lblNCAccX = gtk_label_new ("X:");
  gtk_widget_set_name (lblNCAccX, "lblNCAccX");
  gtk_widget_show (lblNCAccX);
  gtk_table_attach (GTK_TABLE (table8), lblNCAccX, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (lblNCAccX, FALSE);
  gtk_misc_set_alignment (GTK_MISC (lblNCAccX), 0, 0.5);

  lblNCAccY = gtk_label_new ("Y:");
  gtk_widget_set_name (lblNCAccY, "lblNCAccY");
  gtk_widget_show (lblNCAccY);
  gtk_table_attach (GTK_TABLE (table8), lblNCAccY, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (lblNCAccY, FALSE);
  gtk_misc_set_alignment (GTK_MISC (lblNCAccY), 0, 0.5);

  lblNCAccZ = gtk_label_new ("Z:");
  gtk_widget_set_name (lblNCAccZ, "lblNCAccZ");
  gtk_widget_show (lblNCAccZ);
  gtk_table_attach (GTK_TABLE (table8), lblNCAccZ, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (lblNCAccZ, FALSE);
  gtk_misc_set_alignment (GTK_MISC (lblNCAccZ), 0, 0.5);

  lblNCAcc = gtk_label_new ("Acc:");
  gtk_widget_set_name (lblNCAcc, "lblNCAcc");
  gtk_widget_show (lblNCAcc);
  gtk_table_attach (GTK_TABLE (table8), lblNCAcc, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (lblNCAcc, FALSE);
  gtk_misc_set_alignment (GTK_MISC (lblNCAcc), 0, 0.5);

  lblNCRoll = gtk_label_new ("Roll:");
  gtk_widget_set_name (lblNCRoll, "lblNCRoll");
  gtk_widget_show (lblNCRoll);
  gtk_table_attach (GTK_TABLE (table8), lblNCRoll, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (lblNCRoll, FALSE);
  gtk_misc_set_alignment (GTK_MISC (lblNCRoll), 0, 0.5);

  lblNCPitch = gtk_label_new ("Pitch:");
  gtk_widget_set_name (lblNCPitch, "lblNCPitch");
  gtk_widget_show (lblNCPitch);
  gtk_table_attach (GTK_TABLE (table8), lblNCPitch, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (lblNCPitch, FALSE);
  gtk_misc_set_alignment (GTK_MISC (lblNCPitch), 0, 0.5);

  lblNCAccXVal = gtk_label_new ("0");
  gtk_widget_set_name (lblNCAccXVal, "lblNCAccXVal");
  gtk_widget_show (lblNCAccXVal);
  gtk_table_attach (GTK_TABLE (table8), lblNCAccXVal, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lblNCAccXVal, 35, -1);
  gtk_widget_set_sensitive (lblNCAccXVal, FALSE);
  gtk_misc_set_alignment (GTK_MISC (lblNCAccXVal), 0, 0.5);

  lblNCAccYVal = gtk_label_new ("0");
  gtk_widget_set_name (lblNCAccYVal, "lblNCAccYVal");
  gtk_widget_show (lblNCAccYVal);
  gtk_table_attach (GTK_TABLE (table8), lblNCAccYVal, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lblNCAccYVal, 35, -1);
  gtk_widget_set_sensitive (lblNCAccYVal, FALSE);
  gtk_misc_set_alignment (GTK_MISC (lblNCAccYVal), 0, 0.5);

  lblNCAccZVal = gtk_label_new ("0");
  gtk_widget_set_name (lblNCAccZVal, "lblNCAccZVal");
  gtk_widget_show (lblNCAccZVal);
  gtk_table_attach (GTK_TABLE (table8), lblNCAccZVal, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lblNCAccZVal, 35, -1);
  gtk_widget_set_sensitive (lblNCAccZVal, FALSE);
  gtk_misc_set_alignment (GTK_MISC (lblNCAccZVal), 0, 0.5);

  lblNCAccVal = gtk_label_new ("0");
  gtk_widget_set_name (lblNCAccVal, "lblNCAccVal");
  gtk_widget_show (lblNCAccVal);
  gtk_table_attach (GTK_TABLE (table8), lblNCAccVal, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lblNCAccVal, 35, -1);
  gtk_widget_set_sensitive (lblNCAccVal, FALSE);
  gtk_misc_set_alignment (GTK_MISC (lblNCAccVal), 0, 0.5);

  lblNCRollVal = gtk_label_new ("0");
  gtk_widget_set_name (lblNCRollVal, "lblNCRollVal");
  gtk_widget_show (lblNCRollVal);
  gtk_table_attach (GTK_TABLE (table8), lblNCRollVal, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lblNCRollVal, 35, -1);
  gtk_widget_set_sensitive (lblNCRollVal, FALSE);
  gtk_misc_set_alignment (GTK_MISC (lblNCRollVal), 0, 0.5);

  lblNCPitchVal = gtk_label_new ("0");
  gtk_widget_set_name (lblNCPitchVal, "lblNCPitchVal");
  gtk_widget_show (lblNCPitchVal);
  gtk_table_attach (GTK_TABLE (table8), lblNCPitchVal, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lblNCPitchVal, 35, -1);
  gtk_widget_set_sensitive (lblNCPitchVal, FALSE);
  gtk_misc_set_alignment (GTK_MISC (lblNCPitchVal), 0, 0.5);

  progNCAccX = gtk_progress_bar_new ();
  gtk_widget_set_name (progNCAccX, "progNCAccX");
  gtk_widget_show (progNCAccX);
  gtk_table_attach (GTK_TABLE (table8), progNCAccX, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (progNCAccX, FALSE);

  progNCAccZ = gtk_progress_bar_new ();
  gtk_widget_set_name (progNCAccZ, "progNCAccZ");
  gtk_widget_show (progNCAccZ);
  gtk_table_attach (GTK_TABLE (table8), progNCAccZ, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (progNCAccZ, FALSE);

  progNCAccY = gtk_progress_bar_new ();
  gtk_widget_set_name (progNCAccY, "progNCAccY");
  gtk_widget_show (progNCAccY);
  gtk_table_attach (GTK_TABLE (table8), progNCAccY, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (progNCAccY, FALSE);

  lblNC = gtk_label_new ("<b>Nunchuk</b>");
  gtk_widget_set_name (lblNC, "lblNC");
  gtk_widget_show (lblNC);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), lblNC);
  gtk_label_set_use_markup (GTK_LABEL (lblNC), TRUE);

  frame5 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame5, "frame5");
  gtk_widget_show (frame5);
  gtk_box_pack_start (GTK_BOX (hbox10), frame5, TRUE, TRUE, 3);

  alignment29 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment29, "alignment29");
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (frame5), alignment29);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment29), 0, 0, 12, 0);

  vbox5 = gtk_vbox_new (FALSE, 5);
  gtk_widget_set_name (vbox5, "vbox5");
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (alignment29), vbox5);

  table9 = gtk_table_new (3, 9, TRUE);
  gtk_widget_set_name (table9, "table9");
  gtk_widget_show (table9);
  gtk_box_pack_start (GTK_BOX (vbox5), table9, TRUE, TRUE, 0);

  alignment15 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment15, "alignment15");
  gtk_widget_show (alignment15);
  gtk_table_attach (GTK_TABLE (table9), alignment15, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  evCCLeft = gtk_event_box_new ();
  gtk_widget_set_name (evCCLeft, "evCCLeft");
  gtk_widget_show (evCCLeft);
  gtk_container_add (GTK_CONTAINER (alignment15), evCCLeft);

  lblCCLeft = gtk_label_new ("Left");
  gtk_widget_set_name (lblCCLeft, "lblCCLeft");
  gtk_widget_show (lblCCLeft);
  gtk_container_add (GTK_CONTAINER (evCCLeft), lblCCLeft);

  alignment16 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment16, "alignment16");
  gtk_widget_show (alignment16);
  gtk_table_attach (GTK_TABLE (table9), alignment16, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  evCCUp = gtk_event_box_new ();
  gtk_widget_set_name (evCCUp, "evCCUp");
  gtk_widget_show (evCCUp);
  gtk_container_add (GTK_CONTAINER (alignment16), evCCUp);

  lblCCUp = gtk_label_new ("Up");
  gtk_widget_set_name (lblCCUp, "lblCCUp");
  gtk_widget_show (lblCCUp);
  gtk_container_add (GTK_CONTAINER (evCCUp), lblCCUp);

  alignment17 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment17, "alignment17");
  gtk_widget_show (alignment17);
  gtk_table_attach (GTK_TABLE (table9), alignment17, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  evCCDown = gtk_event_box_new ();
  gtk_widget_set_name (evCCDown, "evCCDown");
  gtk_widget_show (evCCDown);
  gtk_container_add (GTK_CONTAINER (alignment17), evCCDown);

  lblCCDown = gtk_label_new ("Down");
  gtk_widget_set_name (lblCCDown, "lblCCDown");
  gtk_widget_show (lblCCDown);
  gtk_container_add (GTK_CONTAINER (evCCDown), lblCCDown);

  alignment18 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment18, "alignment18");
  gtk_widget_show (alignment18);
  gtk_table_attach (GTK_TABLE (table9), alignment18, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  evCCRight = gtk_event_box_new ();
  gtk_widget_set_name (evCCRight, "evCCRight");
  gtk_widget_show (evCCRight);
  gtk_container_add (GTK_CONTAINER (alignment18), evCCRight);

  lblCCRight = gtk_label_new ("Right");
  gtk_widget_set_name (lblCCRight, "lblCCRight");
  gtk_widget_show (lblCCRight);
  gtk_container_add (GTK_CONTAINER (evCCRight), lblCCRight);

  alignment19 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment19, "alignment19");
  gtk_widget_show (alignment19);
  gtk_table_attach (GTK_TABLE (table9), alignment19, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  evCCMinus = gtk_event_box_new ();
  gtk_widget_set_name (evCCMinus, "evCCMinus");
  gtk_widget_show (evCCMinus);
  gtk_container_add (GTK_CONTAINER (alignment19), evCCMinus);

  lblCCMinus = gtk_label_new ("-");
  gtk_widget_set_name (lblCCMinus, "lblCCMinus");
  gtk_widget_show (lblCCMinus);
  gtk_container_add (GTK_CONTAINER (evCCMinus), lblCCMinus);

  alignment20 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment20, "alignment20");
  gtk_widget_show (alignment20);
  gtk_table_attach (GTK_TABLE (table9), alignment20, 4, 5, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  evCCHome = gtk_event_box_new ();
  gtk_widget_set_name (evCCHome, "evCCHome");
  gtk_widget_show (evCCHome);
  gtk_container_add (GTK_CONTAINER (alignment20), evCCHome);

  lblCCHome = gtk_label_new ("Home");
  gtk_widget_set_name (lblCCHome, "lblCCHome");
  gtk_widget_show (lblCCHome);
  gtk_container_add (GTK_CONTAINER (evCCHome), lblCCHome);

  alignment21 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment21, "alignment21");
  gtk_widget_show (alignment21);
  gtk_table_attach (GTK_TABLE (table9), alignment21, 5, 6, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  evCCPlus = gtk_event_box_new ();
  gtk_widget_set_name (evCCPlus, "evCCPlus");
  gtk_widget_show (evCCPlus);
  gtk_container_add (GTK_CONTAINER (alignment21), evCCPlus);

  lblCCPlus = gtk_label_new ("+");
  gtk_widget_set_name (lblCCPlus, "lblCCPlus");
  gtk_widget_show (lblCCPlus);
  gtk_container_add (GTK_CONTAINER (evCCPlus), lblCCPlus);

  alignment22 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment22, "alignment22");
  gtk_widget_show (alignment22);
  gtk_table_attach (GTK_TABLE (table9), alignment22, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  evCCZL = gtk_event_box_new ();
  gtk_widget_set_name (evCCZL, "evCCZL");
  gtk_widget_show (evCCZL);
  gtk_container_add (GTK_CONTAINER (alignment22), evCCZL);

  lblCCZL = gtk_label_new ("ZL");
  gtk_widget_set_name (lblCCZL, "lblCCZL");
  gtk_widget_show (lblCCZL);
  gtk_container_add (GTK_CONTAINER (evCCZL), lblCCZL);

  alignment23 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment23, "alignment23");
  gtk_widget_show (alignment23);
  gtk_table_attach (GTK_TABLE (table9), alignment23, 5, 6, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  evCCZR = gtk_event_box_new ();
  gtk_widget_set_name (evCCZR, "evCCZR");
  gtk_widget_show (evCCZR);
  gtk_container_add (GTK_CONTAINER (alignment23), evCCZR);

  lblCCZR = gtk_label_new ("ZR");
  gtk_widget_set_name (lblCCZR, "lblCCZR");
  gtk_widget_show (lblCCZR);
  gtk_container_add (GTK_CONTAINER (evCCZR), lblCCZR);

  alignment24 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment24, "alignment24");
  gtk_widget_show (alignment24);
  gtk_table_attach (GTK_TABLE (table9), alignment24, 7, 8, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  evCCX = gtk_event_box_new ();
  gtk_widget_set_name (evCCX, "evCCX");
  gtk_widget_show (evCCX);
  gtk_container_add (GTK_CONTAINER (alignment24), evCCX);

  lblCCX = gtk_label_new ("X");
  gtk_widget_set_name (lblCCX, "lblCCX");
  gtk_widget_show (lblCCX);
  gtk_container_add (GTK_CONTAINER (evCCX), lblCCX);

  alignment25 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment25, "alignment25");
  gtk_widget_show (alignment25);
  gtk_table_attach (GTK_TABLE (table9), alignment25, 6, 7, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  evCCY = gtk_event_box_new ();
  gtk_widget_set_name (evCCY, "evCCY");
  gtk_widget_show (evCCY);
  gtk_container_add (GTK_CONTAINER (alignment25), evCCY);

  lblCCY = gtk_label_new ("Y");
  gtk_widget_set_name (lblCCY, "lblCCY");
  gtk_widget_show (lblCCY);
  gtk_container_add (GTK_CONTAINER (evCCY), lblCCY);

  alignment26 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment26, "alignment26");
  gtk_widget_show (alignment26);
  gtk_table_attach (GTK_TABLE (table9), alignment26, 7, 8, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  evCCB = gtk_event_box_new ();
  gtk_widget_set_name (evCCB, "evCCB");
  gtk_widget_show (evCCB);
  gtk_container_add (GTK_CONTAINER (alignment26), evCCB);

  lblCCB = gtk_label_new ("B");
  gtk_widget_set_name (lblCCB, "lblCCB");
  gtk_widget_show (lblCCB);
  gtk_container_add (GTK_CONTAINER (evCCB), lblCCB);

  alignment27 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment27, "alignment27");
  gtk_widget_show (alignment27);
  gtk_table_attach (GTK_TABLE (table9), alignment27, 8, 9, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  evCCA = gtk_event_box_new ();
  gtk_widget_set_name (evCCA, "evCCA");
  gtk_widget_show (evCCA);
  gtk_container_add (GTK_CONTAINER (alignment27), evCCA);

  lblCCA = gtk_label_new ("A");
  gtk_widget_set_name (lblCCA, "lblCCA");
  gtk_widget_show (lblCCA);
  gtk_container_add (GTK_CONTAINER (evCCA), lblCCA);

  hbox15 = gtk_hbox_new (FALSE, 5);
  gtk_widget_set_name (hbox15, "hbox15");
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox15, TRUE, TRUE, 0);

  drawCCLStick = gtk_drawing_area_new ();
  gtk_widget_set_name (drawCCLStick, "drawCCLStick");
  gtk_widget_show (drawCCLStick);
  gtk_box_pack_start (GTK_BOX (hbox15), drawCCLStick, TRUE, TRUE, 0);
  gtk_widget_set_size_request (drawCCLStick, 50, 50);

  drawCCRStick = gtk_drawing_area_new ();
  gtk_widget_set_name (drawCCRStick, "drawCCRStick");
  gtk_widget_show (drawCCRStick);
  gtk_box_pack_start (GTK_BOX (hbox15), drawCCRStick, TRUE, TRUE, 0);
  gtk_widget_set_size_request (drawCCRStick, 50, 50);

  table10 = gtk_table_new (2, 3, FALSE);
  gtk_widget_set_name (table10, "table10");
  gtk_widget_show (table10);
  gtk_box_pack_start (GTK_BOX (hbox15), table10, TRUE, TRUE, 0);

  lblCCLVal = gtk_label_new ("0");
  gtk_widget_set_name (lblCCLVal, "lblCCLVal");
  gtk_widget_show (lblCCLVal);
  gtk_table_attach (GTK_TABLE (table10), lblCCLVal, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lblCCLVal, 35, -1);
  gtk_misc_set_alignment (GTK_MISC (lblCCLVal), 0, 0.5);

  lblCCRVal = gtk_label_new ("0");
  gtk_widget_set_name (lblCCRVal, "lblCCRVal");
  gtk_widget_show (lblCCRVal);
  gtk_table_attach (GTK_TABLE (table10), lblCCRVal, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lblCCRVal, 35, -1);
  gtk_misc_set_alignment (GTK_MISC (lblCCRVal), 0, 0.5);

  progCCL = gtk_progress_bar_new ();
  gtk_widget_set_name (progCCL, "progCCL");
  gtk_widget_show (progCCL);
  gtk_table_attach (GTK_TABLE (table10), progCCL, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  progCCR = gtk_progress_bar_new ();
  gtk_widget_set_name (progCCR, "progCCR");
  gtk_widget_show (progCCR);
  gtk_table_attach (GTK_TABLE (table10), progCCR, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  evCCR = gtk_event_box_new ();
  gtk_widget_set_name (evCCR, "evCCR");
  gtk_widget_show (evCCR);
  gtk_table_attach (GTK_TABLE (table10), evCCR, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lblCCR = gtk_label_new ("R:");
  gtk_widget_set_name (lblCCR, "lblCCR");
  gtk_widget_show (lblCCR);
  gtk_container_add (GTK_CONTAINER (evCCR), lblCCR);
  gtk_misc_set_alignment (GTK_MISC (lblCCR), 0, 0.5);

  evCCL = gtk_event_box_new ();
  gtk_widget_set_name (evCCL, "evCCL");
  gtk_widget_show (evCCL);
  gtk_table_attach (GTK_TABLE (table10), evCCL, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lblCCL = gtk_label_new ("L:");
  gtk_widget_set_name (lblCCL, "lblCCL");
  gtk_widget_show (lblCCL);
  gtk_container_add (GTK_CONTAINER (evCCL), lblCCL);
  gtk_misc_set_alignment (GTK_MISC (lblCCL), 0, 0.5);

  lblClassic = gtk_label_new ("<b>Classic Controller</b>");
  gtk_widget_set_name (lblClassic, "lblClassic");
  gtk_widget_show (lblClassic);
  gtk_frame_set_label_widget (GTK_FRAME (frame5), lblClassic);
  gtk_label_set_use_markup (GTK_LABEL (lblClassic), TRUE);

  hbox11 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox11, "hbox11");
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox11, FALSE, FALSE, 0);

  statConnection = gtk_statusbar_new ();
  gtk_widget_set_name (statConnection, "statConnection");
  gtk_widget_show (statConnection);
  gtk_box_pack_start (GTK_BOX (hbox11), statConnection, TRUE, TRUE, 0);
  gtk_statusbar_set_has_resize_grip (GTK_STATUSBAR (statConnection), FALSE);

  statBattery = gtk_statusbar_new ();
  gtk_widget_set_name (statBattery, "statBattery");
  gtk_widget_show (statBattery);
  gtk_box_pack_start (GTK_BOX (hbox11), statBattery, FALSE, TRUE, 0);
  gtk_statusbar_set_has_resize_grip (GTK_STATUSBAR (statBattery), FALSE);

  statExtension = gtk_statusbar_new ();
  gtk_widget_set_name (statExtension, "statExtension");
  gtk_widget_show (statExtension);
  gtk_box_pack_start (GTK_BOX (hbox11), statExtension, FALSE, TRUE, 0);
  gtk_statusbar_set_has_resize_grip (GTK_STATUSBAR (statExtension), FALSE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (winMain, winMain, "winMain");
  GLADE_HOOKUP_OBJECT (winMain, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (winMain, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (winMain, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (winMain, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (winMain, menuConnect, "menuConnect");
  GLADE_HOOKUP_OBJECT (winMain, image27, "image27");
  GLADE_HOOKUP_OBJECT (winMain, menuDisconnect, "menuDisconnect");
  GLADE_HOOKUP_OBJECT (winMain, image28, "image28");
  GLADE_HOOKUP_OBJECT (winMain, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (winMain, menuQuit, "menuQuit");
  GLADE_HOOKUP_OBJECT (winMain, image29, "image29");
  GLADE_HOOKUP_OBJECT (winMain, menuSettings, "menuSettings");
  GLADE_HOOKUP_OBJECT (winMain, menuSettings_menu, "menuSettings_menu");
  GLADE_HOOKUP_OBJECT (winMain, chkAcc, "chkAcc");
  GLADE_HOOKUP_OBJECT (winMain, chkIR, "chkIR");
  GLADE_HOOKUP_OBJECT (winMain, chkExt, "chkExt");
  GLADE_HOOKUP_OBJECT (winMain, menuControls, "menuControls");
  GLADE_HOOKUP_OBJECT (winMain, menuControls_menu, "menuControls_menu");
  GLADE_HOOKUP_OBJECT (winMain, chkLED1, "chkLED1");
  GLADE_HOOKUP_OBJECT (winMain, chkLED2, "chkLED2");
  GLADE_HOOKUP_OBJECT (winMain, chkLED3, "chkLED3");
  GLADE_HOOKUP_OBJECT (winMain, chkLED4, "chkLED4");
  GLADE_HOOKUP_OBJECT (winMain, separator1, "separator1");
  GLADE_HOOKUP_OBJECT (winMain, chkRumble, "chkRumble");
  GLADE_HOOKUP_OBJECT (winMain, menuView, "menuView");
  GLADE_HOOKUP_OBJECT (winMain, menuView_menu, "menuView_menu");
  GLADE_HOOKUP_OBJECT (winMain, menuRW, "menuRW");
  GLADE_HOOKUP_OBJECT (winMain, menuHelp, "menuHelp");
  GLADE_HOOKUP_OBJECT (winMain, menuHelp_menu, "menuHelp_menu");
  GLADE_HOOKUP_OBJECT (winMain, menuAbout, "menuAbout");
  GLADE_HOOKUP_OBJECT (winMain, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (winMain, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (winMain, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (winMain, table1, "table1");
  GLADE_HOOKUP_OBJECT (winMain, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (winMain, evUp, "evUp");
  GLADE_HOOKUP_OBJECT (winMain, lblUp, "lblUp");
  GLADE_HOOKUP_OBJECT (winMain, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (winMain, evLeft, "evLeft");
  GLADE_HOOKUP_OBJECT (winMain, lblLeft, "lblLeft");
  GLADE_HOOKUP_OBJECT (winMain, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (winMain, evRight, "evRight");
  GLADE_HOOKUP_OBJECT (winMain, lblRight, "lblRight");
  GLADE_HOOKUP_OBJECT (winMain, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (winMain, evDown, "evDown");
  GLADE_HOOKUP_OBJECT (winMain, lblDown, "lblDown");
  GLADE_HOOKUP_OBJECT (winMain, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (winMain, evA, "evA");
  GLADE_HOOKUP_OBJECT (winMain, lblA, "lblA");
  GLADE_HOOKUP_OBJECT (winMain, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (winMain, evB, "evB");
  GLADE_HOOKUP_OBJECT (winMain, lblB, "lblB");
  GLADE_HOOKUP_OBJECT (winMain, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (winMain, evMinus, "evMinus");
  GLADE_HOOKUP_OBJECT (winMain, lblMinus, "lblMinus");
  GLADE_HOOKUP_OBJECT (winMain, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (winMain, evHome, "evHome");
  GLADE_HOOKUP_OBJECT (winMain, lblHome, "lblHome");
  GLADE_HOOKUP_OBJECT (winMain, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (winMain, evPlus, "evPlus");
  GLADE_HOOKUP_OBJECT (winMain, lblPlus, "lblPlus");
  GLADE_HOOKUP_OBJECT (winMain, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (winMain, ev1, "ev1");
  GLADE_HOOKUP_OBJECT (winMain, lbl1, "lbl1");
  GLADE_HOOKUP_OBJECT (winMain, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (winMain, ev2, "ev2");
  GLADE_HOOKUP_OBJECT (winMain, lbl2, "lbl2");
  GLADE_HOOKUP_OBJECT (winMain, label1, "label1");
  GLADE_HOOKUP_OBJECT (winMain, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (winMain, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (winMain, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (winMain, table4, "table4");
  GLADE_HOOKUP_OBJECT (winMain, progAccX, "progAccX");
  GLADE_HOOKUP_OBJECT (winMain, progAccY, "progAccY");
  GLADE_HOOKUP_OBJECT (winMain, progAccZ, "progAccZ");
  GLADE_HOOKUP_OBJECT (winMain, lblAccX, "lblAccX");
  GLADE_HOOKUP_OBJECT (winMain, lblAccXVal, "lblAccXVal");
  GLADE_HOOKUP_OBJECT (winMain, lblAccY, "lblAccY");
  GLADE_HOOKUP_OBJECT (winMain, lblAccYVal, "lblAccYVal");
  GLADE_HOOKUP_OBJECT (winMain, lblAccZ, "lblAccZ");
  GLADE_HOOKUP_OBJECT (winMain, lblAccZVal, "lblAccZVal");
  GLADE_HOOKUP_OBJECT (winMain, lblPitch, "lblPitch");
  GLADE_HOOKUP_OBJECT (winMain, lblPitchVal, "lblPitchVal");
  GLADE_HOOKUP_OBJECT (winMain, lblRoll, "lblRoll");
  GLADE_HOOKUP_OBJECT (winMain, lblRollVal, "lblRollVal");
  GLADE_HOOKUP_OBJECT (winMain, lblAcc, "lblAcc");
  GLADE_HOOKUP_OBJECT (winMain, lblAccVal, "lblAccVal");
  GLADE_HOOKUP_OBJECT (winMain, btnBeep, "btnBeep");
  GLADE_HOOKUP_OBJECT (winMain, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (winMain, drawIR, "drawIR");
  GLADE_HOOKUP_OBJECT (winMain, lblIR, "lblIR");
  GLADE_HOOKUP_OBJECT (winMain, label2, "label2");
  GLADE_HOOKUP_OBJECT (winMain, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (winMain, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (winMain, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (winMain, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (winMain, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (winMain, drawNCStick, "drawNCStick");
  GLADE_HOOKUP_OBJECT (winMain, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (winMain, evNCC, "evNCC");
  GLADE_HOOKUP_OBJECT (winMain, lblNCC, "lblNCC");
  GLADE_HOOKUP_OBJECT (winMain, evNCZ, "evNCZ");
  GLADE_HOOKUP_OBJECT (winMain, lblNCZ, "lblNCZ");
  GLADE_HOOKUP_OBJECT (winMain, table8, "table8");
  GLADE_HOOKUP_OBJECT (winMain, lblNCAccX, "lblNCAccX");
  GLADE_HOOKUP_OBJECT (winMain, lblNCAccY, "lblNCAccY");
  GLADE_HOOKUP_OBJECT (winMain, lblNCAccZ, "lblNCAccZ");
  GLADE_HOOKUP_OBJECT (winMain, lblNCAcc, "lblNCAcc");
  GLADE_HOOKUP_OBJECT (winMain, lblNCRoll, "lblNCRoll");
  GLADE_HOOKUP_OBJECT (winMain, lblNCPitch, "lblNCPitch");
  GLADE_HOOKUP_OBJECT (winMain, lblNCAccXVal, "lblNCAccXVal");
  GLADE_HOOKUP_OBJECT (winMain, lblNCAccYVal, "lblNCAccYVal");
  GLADE_HOOKUP_OBJECT (winMain, lblNCAccZVal, "lblNCAccZVal");
  GLADE_HOOKUP_OBJECT (winMain, lblNCAccVal, "lblNCAccVal");
  GLADE_HOOKUP_OBJECT (winMain, lblNCRollVal, "lblNCRollVal");
  GLADE_HOOKUP_OBJECT (winMain, lblNCPitchVal, "lblNCPitchVal");
  GLADE_HOOKUP_OBJECT (winMain, progNCAccX, "progNCAccX");
  GLADE_HOOKUP_OBJECT (winMain, progNCAccZ, "progNCAccZ");
  GLADE_HOOKUP_OBJECT (winMain, progNCAccY, "progNCAccY");
  GLADE_HOOKUP_OBJECT (winMain, lblNC, "lblNC");
  GLADE_HOOKUP_OBJECT (winMain, frame5, "frame5");
  GLADE_HOOKUP_OBJECT (winMain, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (winMain, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (winMain, table9, "table9");
  GLADE_HOOKUP_OBJECT (winMain, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (winMain, evCCLeft, "evCCLeft");
  GLADE_HOOKUP_OBJECT (winMain, lblCCLeft, "lblCCLeft");
  GLADE_HOOKUP_OBJECT (winMain, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (winMain, evCCUp, "evCCUp");
  GLADE_HOOKUP_OBJECT (winMain, lblCCUp, "lblCCUp");
  GLADE_HOOKUP_OBJECT (winMain, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (winMain, evCCDown, "evCCDown");
  GLADE_HOOKUP_OBJECT (winMain, lblCCDown, "lblCCDown");
  GLADE_HOOKUP_OBJECT (winMain, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (winMain, evCCRight, "evCCRight");
  GLADE_HOOKUP_OBJECT (winMain, lblCCRight, "lblCCRight");
  GLADE_HOOKUP_OBJECT (winMain, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (winMain, evCCMinus, "evCCMinus");
  GLADE_HOOKUP_OBJECT (winMain, lblCCMinus, "lblCCMinus");
  GLADE_HOOKUP_OBJECT (winMain, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (winMain, evCCHome, "evCCHome");
  GLADE_HOOKUP_OBJECT (winMain, lblCCHome, "lblCCHome");
  GLADE_HOOKUP_OBJECT (winMain, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (winMain, evCCPlus, "evCCPlus");
  GLADE_HOOKUP_OBJECT (winMain, lblCCPlus, "lblCCPlus");
  GLADE_HOOKUP_OBJECT (winMain, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (winMain, evCCZL, "evCCZL");
  GLADE_HOOKUP_OBJECT (winMain, lblCCZL, "lblCCZL");
  GLADE_HOOKUP_OBJECT (winMain, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (winMain, evCCZR, "evCCZR");
  GLADE_HOOKUP_OBJECT (winMain, lblCCZR, "lblCCZR");
  GLADE_HOOKUP_OBJECT (winMain, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (winMain, evCCX, "evCCX");
  GLADE_HOOKUP_OBJECT (winMain, lblCCX, "lblCCX");
  GLADE_HOOKUP_OBJECT (winMain, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (winMain, evCCY, "evCCY");
  GLADE_HOOKUP_OBJECT (winMain, lblCCY, "lblCCY");
  GLADE_HOOKUP_OBJECT (winMain, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (winMain, evCCB, "evCCB");
  GLADE_HOOKUP_OBJECT (winMain, lblCCB, "lblCCB");
  GLADE_HOOKUP_OBJECT (winMain, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (winMain, evCCA, "evCCA");
  GLADE_HOOKUP_OBJECT (winMain, lblCCA, "lblCCA");
  GLADE_HOOKUP_OBJECT (winMain, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (winMain, drawCCLStick, "drawCCLStick");
  GLADE_HOOKUP_OBJECT (winMain, drawCCRStick, "drawCCRStick");
  GLADE_HOOKUP_OBJECT (winMain, table10, "table10");
  GLADE_HOOKUP_OBJECT (winMain, lblCCLVal, "lblCCLVal");
  GLADE_HOOKUP_OBJECT (winMain, lblCCRVal, "lblCCRVal");
  GLADE_HOOKUP_OBJECT (winMain, progCCL, "progCCL");
  GLADE_HOOKUP_OBJECT (winMain, progCCR, "progCCR");
  GLADE_HOOKUP_OBJECT (winMain, evCCR, "evCCR");
  GLADE_HOOKUP_OBJECT (winMain, lblCCR, "lblCCR");
  GLADE_HOOKUP_OBJECT (winMain, evCCL, "evCCL");
  GLADE_HOOKUP_OBJECT (winMain, lblCCL, "lblCCL");
  GLADE_HOOKUP_OBJECT (winMain, lblClassic, "lblClassic");
  GLADE_HOOKUP_OBJECT (winMain, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (winMain, statConnection, "statConnection");
  GLADE_HOOKUP_OBJECT (winMain, statBattery, "statBattery");
  GLADE_HOOKUP_OBJECT (winMain, statExtension, "statExtension");

  gtk_window_add_accel_group (GTK_WINDOW (winMain), accel_group);

  return winMain;
}

GtkWidget*
create_winRW (void)
{
  GtkWidget *winRW;
  GtkWidget *vbox3;
  GtkWidget *label25;
  GtkWidget *hbox3;
  GtkWidget *table6;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *txtReadOffset;
  GtkWidget *txtReadLen;
  GtkWidget *radReadEEPROM;
  GSList *radReadEEPROM_group = NULL;
  GtkWidget *radReadReg;
  GtkWidget *hbox7;
  GtkWidget *btnRead;
  GtkWidget *hbox4;
  GtkWidget *label31;
  GtkWidget *table7;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *txtWriteOffset;
  GtkWidget *txtWriteData;
  GtkWidget *radWriteEEPROM;
  GSList *radWriteEEPROM_group = NULL;
  GtkWidget *radWriteReg;
  GtkWidget *hbox8;
  GtkWidget *btnWrite;
  GtkWidget *hbox6;
  GtkWidget *label32;
  GtkWidget *scrolledwindow1;
  GtkWidget *tvRW;
  GtkWidget *hbox9;
  GtkWidget *btnRWClose;

  winRW = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (winRW, "winRW");
  gtk_window_set_title (GTK_WINDOW (winRW), "Memory Read/Write");

  vbox3 = gtk_vbox_new (FALSE, 4);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (winRW), vbox3);
  gtk_container_set_border_width (GTK_CONTAINER (vbox3), 5);

  label25 = gtk_label_new ("Note: all values are in hex");
  gtk_widget_set_name (label25, "label25");
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (vbox3), label25, FALSE, FALSE, 0);

  hbox3 = gtk_hbox_new (FALSE, 5);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox3, FALSE, TRUE, 0);

  table6 = gtk_table_new (6, 2, FALSE);
  gtk_widget_set_name (table6, "table6");
  gtk_widget_show (table6);
  gtk_box_pack_start (GTK_BOX (hbox3), table6, TRUE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table6), 2);

  label29 = gtk_label_new ("Offset:");
  gtk_widget_set_name (label29, "label29");
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table6), label29, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  label30 = gtk_label_new ("Length:");
  gtk_widget_set_name (label30, "label30");
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table6), label30, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  txtReadOffset = gtk_entry_new ();
  gtk_widget_set_name (txtReadOffset, "txtReadOffset");
  gtk_widget_show (txtReadOffset);
  gtk_table_attach (GTK_TABLE (table6), txtReadOffset, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  txtReadLen = gtk_entry_new ();
  gtk_widget_set_name (txtReadLen, "txtReadLen");
  gtk_widget_show (txtReadLen);
  gtk_table_attach (GTK_TABLE (table6), txtReadLen, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radReadEEPROM = gtk_radio_button_new_with_mnemonic (NULL, "EEPROM");
  gtk_widget_set_name (radReadEEPROM, "radReadEEPROM");
  gtk_widget_show (radReadEEPROM);
  gtk_table_attach (GTK_TABLE (table6), radReadEEPROM, 0, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radReadEEPROM), radReadEEPROM_group);
  radReadEEPROM_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radReadEEPROM));

  radReadReg = gtk_radio_button_new_with_mnemonic (NULL, "Register");
  gtk_widget_set_name (radReadReg, "radReadReg");
  gtk_widget_show (radReadReg);
  gtk_table_attach (GTK_TABLE (table6), radReadReg, 0, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radReadReg), radReadEEPROM_group);
  radReadEEPROM_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radReadReg));

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox7, "hbox7");
  gtk_widget_show (hbox7);
  gtk_table_attach (GTK_TABLE (table6), hbox7, 0, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  btnRead = gtk_button_new_with_mnemonic ("Read");
  gtk_widget_set_name (btnRead, "btnRead");
  gtk_widget_show (btnRead);
  gtk_box_pack_start (GTK_BOX (hbox7), btnRead, TRUE, FALSE, 0);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_widget_show (hbox4);
  gtk_table_attach (GTK_TABLE (table6), hbox4, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label31 = gtk_label_new ("Read");
  gtk_widget_set_name (label31, "label31");
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox4), label31, TRUE, FALSE, 0);

  table7 = gtk_table_new (6, 2, FALSE);
  gtk_widget_set_name (table7, "table7");
  gtk_widget_show (table7);
  gtk_box_pack_start (GTK_BOX (hbox3), table7, TRUE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table7), 2);

  label33 = gtk_label_new ("Offset:");
  gtk_widget_set_name (label33, "label33");
  gtk_widget_show (label33);
  gtk_table_attach (GTK_TABLE (table7), label33, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label33), 0, 0.5);

  label34 = gtk_label_new ("Data:");
  gtk_widget_set_name (label34, "label34");
  gtk_widget_show (label34);
  gtk_table_attach (GTK_TABLE (table7), label34, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label34), 0, 0.5);

  txtWriteOffset = gtk_entry_new ();
  gtk_widget_set_name (txtWriteOffset, "txtWriteOffset");
  gtk_widget_show (txtWriteOffset);
  gtk_table_attach (GTK_TABLE (table7), txtWriteOffset, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  txtWriteData = gtk_entry_new ();
  gtk_widget_set_name (txtWriteData, "txtWriteData");
  gtk_widget_show (txtWriteData);
  gtk_table_attach (GTK_TABLE (table7), txtWriteData, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radWriteEEPROM = gtk_radio_button_new_with_mnemonic (NULL, "EEPROM");
  gtk_widget_set_name (radWriteEEPROM, "radWriteEEPROM");
  gtk_widget_show (radWriteEEPROM);
  gtk_table_attach (GTK_TABLE (table7), radWriteEEPROM, 0, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radWriteEEPROM), radWriteEEPROM_group);
  radWriteEEPROM_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radWriteEEPROM));

  radWriteReg = gtk_radio_button_new_with_mnemonic (NULL, "Register");
  gtk_widget_set_name (radWriteReg, "radWriteReg");
  gtk_widget_show (radWriteReg);
  gtk_table_attach (GTK_TABLE (table7), radWriteReg, 0, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radWriteReg), radWriteEEPROM_group);
  radWriteEEPROM_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radWriteReg));

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox8, "hbox8");
  gtk_widget_show (hbox8);
  gtk_table_attach (GTK_TABLE (table7), hbox8, 0, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  btnWrite = gtk_button_new_with_mnemonic ("Write");
  gtk_widget_set_name (btnWrite, "btnWrite");
  gtk_widget_show (btnWrite);
  gtk_box_pack_start (GTK_BOX (hbox8), btnWrite, TRUE, FALSE, 0);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox6, "hbox6");
  gtk_widget_show (hbox6);
  gtk_table_attach (GTK_TABLE (table7), hbox6, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label32 = gtk_label_new ("Write");
  gtk_widget_set_name (label32, "label32");
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox6), label32, TRUE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox3), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  tvRW = gtk_text_view_new ();
  gtk_widget_set_name (tvRW, "tvRW");
  gtk_widget_show (tvRW);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), tvRW);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox9, "hbox9");
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox9, FALSE, TRUE, 0);

  btnRWClose = gtk_button_new_with_mnemonic ("Close");
  gtk_widget_set_name (btnRWClose, "btnRWClose");
  gtk_widget_show (btnRWClose);
  gtk_box_pack_start (GTK_BOX (hbox9), btnRWClose, TRUE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (winRW, winRW, "winRW");
  GLADE_HOOKUP_OBJECT (winRW, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (winRW, label25, "label25");
  GLADE_HOOKUP_OBJECT (winRW, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (winRW, table6, "table6");
  GLADE_HOOKUP_OBJECT (winRW, label29, "label29");
  GLADE_HOOKUP_OBJECT (winRW, label30, "label30");
  GLADE_HOOKUP_OBJECT (winRW, txtReadOffset, "txtReadOffset");
  GLADE_HOOKUP_OBJECT (winRW, txtReadLen, "txtReadLen");
  GLADE_HOOKUP_OBJECT (winRW, radReadEEPROM, "radReadEEPROM");
  GLADE_HOOKUP_OBJECT (winRW, radReadReg, "radReadReg");
  GLADE_HOOKUP_OBJECT (winRW, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (winRW, btnRead, "btnRead");
  GLADE_HOOKUP_OBJECT (winRW, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (winRW, label31, "label31");
  GLADE_HOOKUP_OBJECT (winRW, table7, "table7");
  GLADE_HOOKUP_OBJECT (winRW, label33, "label33");
  GLADE_HOOKUP_OBJECT (winRW, label34, "label34");
  GLADE_HOOKUP_OBJECT (winRW, txtWriteOffset, "txtWriteOffset");
  GLADE_HOOKUP_OBJECT (winRW, txtWriteData, "txtWriteData");
  GLADE_HOOKUP_OBJECT (winRW, radWriteEEPROM, "radWriteEEPROM");
  GLADE_HOOKUP_OBJECT (winRW, radWriteReg, "radWriteReg");
  GLADE_HOOKUP_OBJECT (winRW, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (winRW, btnWrite, "btnWrite");
  GLADE_HOOKUP_OBJECT (winRW, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (winRW, label32, "label32");
  GLADE_HOOKUP_OBJECT (winRW, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (winRW, tvRW, "tvRW");
  GLADE_HOOKUP_OBJECT (winRW, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (winRW, btnRWClose, "btnRWClose");

  return winRW;
}

