#!/bin/sh
# rsync the CVS source files from SourceForge to make a local copy

# the source dir where this script is
SCRIPT_DIR=$(echo $0 | sed 's|\(.*\)/.*$|\1|')
. $SCRIPT_DIR/auto-build-common

# the name of this script
SCRIPT=$(echo $0| sed 's|.*/\(.*\)|\1|g')

LOGFILE=/home/pd/logs/${DATE}_${TIME}_-_${SCRIPT}_-_${SYSTEM}.txt

VERBOSE_FLAGS=-v
#VERBOSE_FLAGS="-v --progress"

touch $LOGFILE

echo "rsync pure-data" >> $LOGFILE 2>&1
echo "----------------------------------------------------------------------" >> $LOGFILE 2>&1
(/usr/bin/rsync -ax $VERBOSE_FLAGS --delete  pure-data.svn.sourceforge.net::svn/pure-data/ /home/pd/svnroot/pure-data/  || /usr/bin/logger -i -p local6.warning -t "$0" "rsync pure-data SVN FAILED") >> $LOGFILE 2>&1

echo "rsync pd-gem" >> $LOGFILE 2>&1
echo "----------------------------------------------------------------------" >> $LOGFILE 2>&1
(/usr/bin/rsync -ax $VERBOSE_FLAGS --delete  rsync://pd-gem.cvs.sourceforge.net/cvsroot/p/pd/pd-gem/ /home/pd/cvsroot/pd-gem  || /usr/bin/logger -i -p local6.warning -t "$0" "rsync pd-gem CVS FAILED") >> $LOGFILE 2>&1

echo "chown -R pd.pd /home/pd/cvsroot" >> $LOGFILE 2>&1
echo "----------------------------------------------------------------------" >> $LOGFILE 2>&1
chown -R pd.pd /home/pd/cvsroot >> $LOGFILE 2>&1

echo "chown -R pd.pd /home/pd/svnroot" >> $LOGFILE 2>&1
echo "----------------------------------------------------------------------" >> $LOGFILE 2>&1
chown -R pd.pd /home/pd/svnroot >> $LOGFILE 2>&1


